### ISSUE TITLE
front: implement more API calls

### ISSUE THREAD

**Issue by moul** [pathwar/pathwar#165]
* using the already implemented `GET /user-session`, you can get the list of available tournaments and their IDs
* now you can call `POST /preferences` and post the following JSON: `{"active_tournament_id":"an-id-of-tournament"}`
* you should then call again `GET /user-session` and you should see the fields `active_tournament_id` updated with the value provided in the previous call; and `active_tournament_team_id` set with your corresponding TournamentTeam if you have one in the selected Tournament, else it's null
* you can list the "global teams" using `GET /teams` which will returns all the global teams (from all the tournaments)
* and you can list the "TournamentTeams of a specific tournament" (the teams you should see in the tournament dashboard) using `GET /tournament/teams?tourmanet_id=XXX`

**Comment by moul** [comment]
Not sure the doc is totally exact, but in case it can help you: https://pathwar.docs.apiary.io/#

**Comment by moul** [comment]
fyi, most of the calls and most of the usage will be "scoped" to the active tournament, so this first `GET /tournament/teams?tournament_id=XXX` can be a good base to make some helpers if you have some in mind

**Comment by lucasgdev** [comment]
@moul I think I got it, I will start by making this behavior of getting a default tournament and post it back, then call the user-session again to see the new fields. Another doubt that I've, I was getting data from the field **user.active_tournament_member** that is returning from /user-session, is just doubt but what this field stands for?

**Comment by lucasgdev** [comment]
@moul I'm getting an error 500 when trying to post on /preferences, even on apiary I wasn't able to make a successful call, here i'm sending a cURL of the request:

`curl 'https://api-dev.pathwar.land/preferences' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://localhost:8000/app/dashboard' -H 'Origin: http://localhost:8000' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36' -H 'Authorization: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJDck10ZmN1cjFDcVNtT28teHZacUt0ZTRoODk4ZjZpYl9KOGk5TXZDck5zIn0.eyJqdGkiOiJlZGMwNmQyMy0xNjgxLTRlZTctOTVlZS04NzQwYjI4YTkwYWUiLCJleHAiOjE1NzA3NjczNDEsIm5iZiI6MCwiaWF0IjoxNTcwNzY3MDQxLCJpc3MiOiJodHRwczovL2lkLnBhdGh3YXIubGFuZC9hdXRoL3JlYWxtcy9QYXRod2FyLURldiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIyNWFhZGU0My1mOWJlLTQ1YTEtYjI0OC0yZDYwNjU5YzA1MmUiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJwbGF0Zm9ybS1mcm9udCIsIm5vbmNlIjoiMTgyMzBlYTMtMDIzZS00MjAyLTgyNTYtY2RmZjY4NjcwMzY0IiwiYXV0aF90aW1lIjoxNTcwNzY1NTAyLCJzZXNzaW9uX3N0YXRlIjoiNjNlOGQwNTEtMDIwMy00ZGM4LTg2Y2YtODE0NWY3MTZkMDczIiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiQWxvaGEgVGVzdGluZyIsInByZWZlcnJlZF91c2VybmFtZSI6ImFsb2hhNCIsImdpdmVuX25hbWUiOiJBbG9oYSIsImZhbWlseV9uYW1lIjoiVGVzdGluZyIsImVtYWlsIjoiYWxvaGE0QG1haWxpbmF0b3IuY29tIn0.L9ou50AfB8WU6leLxPrk5p-GZZ8nSjgPuQb0q0VjvRpE99OYXlxCTtkLiyinJP-b_A9DahOvmYLCHBAqQv7VK2oea1tIRfJ4HHFWRKseMMePjrzdPEi6T_pSi4df_mHltPB2H3bcl2RIQIkZOG676vZyAe-4oi_78Eg_ybV1xwy3aGhlR1GMluQ8B1K0e2EJfP2gu5nESMGHbRblanDYDbGNHE87EdBAQOjMwxguknLHexnmSSrDz6crllyo4DpU0lx8uLirHVRH08Z1w0yA4vQavzetCYI9C5zvElqlDOujCkkqWhBaZE50_KcGWdMSC0d115FILL4feXwa_0FxBw' -H 'Sec-Fetch-Mode: cors' -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"active_tournament_id":"+bX6YU45Sg+AFln1TOUFxA=="}' --compressed`

**Comment by moul** [comment]
Fixed with https://github.com/pathwar/pathwar/pull/169

**Comment by lucasgdev** [comment]
@moul The post on preferences is working nice, but when I call /user-session again I'm getting this:

**active_tournament_id - cool
active_tournament_member
active_tournament_member_id**

but no **active_tournament_team_id**

![image](https://user-images.githubusercontent.com/6627610/66789241-264a1980-eec1-11e9-984c-5d1cd4911652.png)

**Comment by lucasgdev** [comment]
@moul Trying to get all teams of a Tournament I'm receiving an error 500, here I'm sending de cURL and an images:

![image](https://user-images.githubusercontent.com/6627610/66791378-606be900-eeca-11e9-9acb-52f6c7bfbb76.png)

![image](https://user-images.githubusercontent.com/6627610/66791383-695cba80-eeca-11e9-8327-681e23eedfcc.png)


`curl 'https://api-dev.pathwar.land/tournament/teams?tournament_id=+bX6YU45Sg+AFln1TOUFxA==' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://localhost:8000/app/tournament' -H 'Origin: http://localhost:8000' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36' -H 'Authorization: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJDck10ZmN1cjFDcVNtT28teHZacUt0ZTRoODk4ZjZpYl9KOGk5TXZDck5zIn0.eyJqdGkiOiJmZmViMmE3YS1jYjYxLTQzMzEtODk0NC1hYzJkOWRkNjM1YTkiLCJleHAiOjE1NzEwOTk4MjksIm5iZiI6MCwiaWF0IjoxNTcxMDk5NTI5LCJpc3MiOiJodHRwczovL2lkLnBhdGh3YXIubGFuZC9hdXRoL3JlYWxtcy9QYXRod2FyLURldiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIyNWFhZGU0My1mOWJlLTQ1YTEtYjI0OC0yZDYwNjU5YzA1MmUiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJwbGF0Zm9ybS1mcm9udCIsIm5vbmNlIjoiYzQwODE0MWMtYzZmZi00MWM4LTgzZjktOTg0MTRiYTE5YWNlIiwiYXV0aF90aW1lIjoxNTcxMDk0Mjg0LCJzZXNzaW9uX3N0YXRlIjoiMmU5ZTMyNDctYzgyNi00NDVkLThhYWMtZDU5ZjZhZGNlOTFkIiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiQWxvaGEgVGVzdGluZyIsInByZWZlcnJlZF91c2VybmFtZSI6ImFsb2hhNCIsImdpdmVuX25hbWUiOiJBbG9oYSIsImZhbWlseV9uYW1lIjoiVGVzdGluZyIsImVtYWlsIjoiYWxvaGE0QG1haWxpbmF0b3IuY29tIn0.QEZ01CbqzoJY2Cfn7NVfBqFPS2wiMxeAlvEAlWxoEpFaeECO6c4TFvw3wI3Laz2EbFOVnTCWhjR7BYyaji_KmxI6u5Saj1zvFQjydK6f8Locr00o6Nq0VvohQxdXqJl22Gw54xTPinUT64JOEm9MYOhGKudiny8mV9ZdPcMrBCQ120ZCXKXANhjHv4wxuC7Wk-nmLaoZu_WtXA-S9yhbxzvrlJQI-J0MvBFE42t57AFbuK7yVJOHKCj2eaIQrZcjTpXlhqoi0HudQsh4df3uBtjDxnPQw6sP9e0WjuemQY2T5JlS0gOTObT03Mz60fQfOR4iereua64QRvO-N1H7lQ' -H 'Sec-Fetch-Mode: cors' --compressed`

**Comment by moul** [comment]
Try to esacpe the tournament_id, I think that special chars are not well handled by the API
