### ISSUE TITLE
feat: handle all types of events

### ISSUE THREAD

**Issue by Mikatech** [pathwar/pathwar#804]
For now the only event which is handle is ``ChallengeSubscriptionValidate`` with updating the score.
Pathwar should handle others events with the package event-sourcing too.

handle these events:
- [ ] UserRegister
- [ ] UserLogin
- [ ] UserSetPreferences
- [ ] UserDeleteAccount
- [ ] SeasonChallengeBuy
- [ ] ChallengeSubscriptionValidate
- [ ] CouponValidate
- [ ] AgentRegister
- [ ] AgentChallengeInstanceCreate
- [ ] AgentChallengeInstanceUpdate
- [ ] TeamCreation
- [ ] TeamInviteSend
- [ ] TeamInviteAccept

**Comment by Mikatech** [comment]
I'm thinking about how implement event sourcing foll events.

For example, currently when you buy a challenge several things are modified (cash, subscription ...) in db and before that several checks are made.

But the answer also allows to display a notification, and to know if the buy has worked.

if for example I put all the logic in the event sourcing, and that the call api linked to the button buy just trigger an event.

How do I display if the buy worked or not?
I could try to wait for my event to be processed for example before returning the call API? or we don't care to notify if the purchase worked?

After some research i could implement a [Server-sent-event](https://github.com/antage/eventsource)
Or i can use Event-sourcing only for score computing ?

Any idea @moul 

Some links which talk about my thinking: 
- [Event-sourcing side effect 1](https://softwareengineering.stackexchange.com/questions/366044/with-event-sourcing-how-to-get-the-response-of-a-call-that-is-a-side-effect)
- [Event-sourcing side effect 2](https://stackoverflow.com/questions/46640925/ddd-event-store-ui/46641833#46641833)

**Comment by moul** [comment]
There are basically two schools: 

- full ES
- progressive/partial ES

The first one is about considering that everything in terms of SQL write is event based; sql is a projection of the current expected state with the current implementation. It's a heavier work at the beginning (probably a way heavier than you think), it involves some risks of making bad decisions and needs to restart. But at the end, it's awesome. And probably the fastest way to become awesome.

The second is about making what we did: make sure to store events for the future, but only implement ES processing pipelines progressively. It allows choosing widely, having more time to think, making smaller mistakes, making life easier in general. Then for me it's not an issue to have tables they are partially directly updated, partially ES processed.

I recommend the second one, but it's up to you, the first one makes sense, especially if you have good feelings that you'll make it.

---

If we go with second option, then a good thing is to consider that most of the actions are updating things in real time without too much pressure. And consider that we can have slower crons that fix eventual inconsistencies.

**Comment by moul** [comment]
And btw, ES allow many async processing, ie making the API asynchronous and replying not the result but a job ID.

This doesn't mean you can keep the API synchronous, by just calling the ES processor and returning the answer.

I strongly suggest you to keep the API as synchronous as possible. Async should be an exception at the current stage.
