### ISSUE TITLE
FEAT: Rules systems for season

### ISSUE THREAD

**Issue by Mikatech** [pathwar/pathwar#847]
I want to create season with some rules, let's start with some basics:
- [x] Be able to limit the number of player per team for a season (optional, no limit if not mentioned)
- [x] Be able to set a start date (optional, start now if not mentioned)
- [x] Be able to set a end date (optional, never end if not mentioned)
- [x] Be able to set a regex whitelist for allow only some people to join (optional, all can  join if not mentioned)
- [x] Be able to set a limit of team in season (optional, no limit if not mentioned)

At a solution, i think about:
- YAML File pass in parameters at the command to create new season
- Add a column (rules_bundle) in season which contains the rules, parse the file and verify the rules (example start date can't be > end date)
- The rule will have an structure with default values
- When user/team want to join/invite to a season, verify that he respect the rule:
  - [x] Team creation
  - [x] Team invite send
  - [x] Team invite accept
- When an action is effectued by a user into a season, verify the rules date
  - [x] Coupon
  - [x] Buy/Validate challenge

About changing the status of season to closed when the date is passed  i imagine many solutions:
- 1 - Each time an action is verified coupon/challenge, if the end date is passed & the status is still open, i set it to close
- 2 - Maybe a solution with SQL Jobs is possible, but not dig for now this solution
- 3 - I run a cronjob which run a little script which check rule of each season and apply needed update
- 4 -(my favorite)  I use a trick and when a season is created I emit an event "closed_season" with as value of `created_at` the value of the end date. This way this event will be processed automatically by the event handler when this date is expired. :star:
Maybe you want to give your opinion on this ? @moul

--- Edit

Need to:

- [x] Add test for each function
- [x] Handle error message in web app
- [x] Push a template of season rule config file

**Comment by moul** [comment]
I like this method.

An alternative approach could be to implement a scripting language that enables users to customize seasons and other elements based on a script stored in a database; however, this is a more complex solution.

I suggest you begin your approach with an emphasis on keeping the code clean and organized. Modular approaches can quickly become unmaintainable if not managed properly. However, there are many effective strategies for keeping the code up-to-date and under control.
