### ISSUE TITLE
[BUG] Buying a challenge without enough coins gives "An error occured" which makes the problem not clear

### ISSUE THREAD

**Issue by LFGaming** [pathwar/pathwar#862]
**Describe the bug**
When trying to buy a challenge without enough coins for that challenge, you get an error message which says `An error occured`. This error message does not make it clear that you don't have enough coins so you could get confused and think that the buy option is broken.

**To Reproduce**
1. Go to challenges.
2. Try to buy a challenge when you don't have enough coins for that challenge.
3. See error message stating "An error occured"

**Expected behavior**
I would expect a popup with something like "You don't have enough coins" or something similar.

**Screenshots / Logs**

https://user-images.githubusercontent.com/38732192/231475799-93c7ea38-d901-4f17-8fd2-5cc0498a5a87.mp4

**Versions (please complete the following information, if relevant):**
The current build on https://pathwar.mikatech.me/

**Comment by Mikatech** [comment]
fix in #866, thanks for your report @LFGaming :heart: 
have a nice day
